CREATE TABLE `NEXILIS_CATEGORY` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` varchar(10) NOT NULL,
  `NAME` varchar(128) NOT NULL,
  `PARENT` varchar(10) DEFAULT NULL,
  `BE_ID` int(11) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

ALTER TABLE `NEXILIS_CATEGORY`   
  ADD  UNIQUE INDEX `CATEGORY_ID` (`CATEGORY_ID`);

ALTER TABLE `WEBFORM`   
	ADD COLUMN `ENABLE_CATEGORY` INT NULL COMMENT 'flag' AFTER `CPAAS_ICON`;


  ALTER TABLE `POST`   
	CHANGE `PRICING` `PRICING` SMALLINT(1) DEFAULT 0 NULL COMMENT '0:post; 1:product; 2:post&product',
	ADD COLUMN `CATEGORY` VARCHAR(10) NULL COMMENT 'nexilis category ID' AFTER `PRICING_MONEY`,
	ADD COLUMN `PARENT` VARCHAR(10) NULL COMMENT 'parent category ID' AFTER `CATEGORY`;

  ALTER TABLE `PRODUCT`   
	ADD COLUMN `PARENT` VARCHAR(10) NULL AFTER `CATEGORY`;



